# Lifecycle of the training process
trainer:
  initialization: scratch   # scratch | imagenet | checkpoint
  max_epochs: 50
  accumulation_steps: 3 # in this way we simulate a batchsize of 12
  eval_freq: 1
  save_checkpoint: True
  num_workers: 4
  batch_size: 4
  precision: "16-mixed"

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  
  lr:
    scratch: 1e-4
    imagenet: 3e-4
    checkpoint: 1e-5

  weight_decay: 1e-5

# Scheduler
scheduler:

    warmup_epochs: 5
    warmup_start_factor: 0.01

    cosine:
      t_max: ${trainer.trainer.max_epochs}

# Scaler for mixed precision training
scaler:
  _target_: torch.cuda.amp.GradScaler
  enabled: true

# Loss Function
loss:
  _target_: monai.losses.DiceFocalLoss # Different from Hemoset author that used a CE Loss for N classes
  sigmoid: True
  gamma: 1.0
  lambda_dice: 0.5
  lambda_focal: 0.5

# Early Stopping
early_stopping:
  patience: 10
  mode: "max"
