# U-NET

## BASELINE

unet:
  architecture:
    _target_: monai.networks.nets.UNet
    spatial_dims: 2
    in_channels: 3
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    num_res_units: 2

  temporal_setting:
    temporal_mode: none

unet_resnet18:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.SMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    use_imagenet_norm: True
    in_channels: 3
    classes: 1

  temporal_setting:
    temporal_mode: none

## EARLY FUSION

### WARM-UP ON

unet_early_fusion_warmup_on:
  architecture:
    _target_: monai.networks.nets.UNet
    spatial_dims: 2
    in_channels: 4 # 3 RGB + 1 Maschera
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    num_res_units: 2
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/UNet/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "early_fusion"
    temporal_target_layer: "model.0.conv.unit0.conv.weight"
    warmup_epochs: 5

unet_resnet18_early_fusion_warmup_on:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.SMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    use_imagenet_norm: True
    in_channels: 4 # 3 RGB + 1 Maschera
    classes: 1
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/SMPUNet/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "early_fusion"
    temporal_target_layer: "model.0.conv.unit0.conv.weight" # Copia i pesi da 3 a 4 canali

  initialization:
    warmup_epochs: 5
    freeze_backbone: True

### WARM-UP OFF

unet_early_fusion_warmup_off:
  
  architecture:
    _target_: monai.networks.nets.UNet
    spatial_dims: 2
    in_channels: 4 # 3 RGB + 1 Maschera
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    num_res_units: 2

  temporal_setting:
    temporal_mode: "early_fusion"
    temporal_target_layer: None
    warmup_epochs: 0

unet_resnet18_early_fusion_warmup_off:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.SMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    use_imagenet_norm: True
    in_channels: 4 # 3 RGB + 1 Maschera
    classes: 1

  temporal_setting:
    temporal_mode: "early_fusion"
    temporal_target_layer: None # Copia i pesi da 3 a 4 canali

  initialization:
    warmup_epochs: 0
    freeze_backbone: True

## LATE FUSION

### WARMUP ON

r_unet_late_fusion_lstm_warmup_on:
  architecture:
    _target_: src.surgical_copilot.models.Recurrent_U_Net.runet.RecurrentUNet
    spatial_dims: 2
    in_channels: 3
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    recurrent_type: "lstm"
    num_res_units: 2
    recurrent_layers: 1  
    freeze_backbone: True
    warmup_epochs: 5
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/UNet/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

r_unet_late_fusion_gru_lstm_warmup_on:
  architecture:
    _target_: src.surgical_copilot.models.Recurrent_U_Net.runet.RecurrentUNet
    spatial_dims: 2
    in_channels: 3
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    recurrent_type: "gru"
    num_res_units: 2
    recurrent_layers: 1  
    freeze_backbone: True
    warmup_epochs: 5
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/UNet/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

r_unet_resnet18_late_fusion_lstm_warmup_on:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.RecurrentSMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1
    recurrent_type: "lstm"
    bottleneck_dim: 512
    freeze_backbone: True
    warmup_epochs: 5
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/SMPUNet/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

r_unet_resnet18_late_fusion_gru_warmup_on:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.RecurrentSMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1
    recurrent_type: "gru"
    bottleneck_dim: 512
    freeze_backbone: True
    warmup_epochs: 5
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/SMPUNet/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

### WARMUP OFF

r_unet_late_fusion_lstm_warmup_off:
  architecture:
    _target_: src.surgical_copilot.models.Recurrent_U_Net.runet.RecurrentUNet
    spatial_dims: 2
    in_channels: 3
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    recurrent_type: "lstm"
    num_res_units: 2
    recurrent_layers: 1  
    freeze_backbone: True
    warmup_epochs: 0
    pretrained_weights_path: None

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

r_unet_late_fusion_gru_warmup_off:
  architecture:
    _target_: src.surgical_copilot.models.Recurrent_U_Net.runet.RecurrentUNet
    spatial_dims: 2
    in_channels: 3
    out_channels: 1
    channels: [32, 64, 128, 256, 512]
    strides: [2, 2, 2, 2]
    recurrent_type: "gru"
    num_res_units: 2
    recurrent_layers: 1  
    freeze_backbone: True
    warmup_epochs: 0
    pretrained_weights_path: None

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

r_unet_resnet18_late_fusion_lstm_warmup_off:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.RecurrentSMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1
    recurrent_type: "lstm"
    bottleneck_dim: 512
    freeze_backbone: True
    warmup_epochs: 0
    pretrained_weights_path: None

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

r_unet_resnet18_late_fusion_gru_warmup_off:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.RecurrentSMPUNet
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1
    recurrent_type: "gru"
    bottleneck_dim: 512
    freeze_backbone: True
    warmup_epochs: 0
    pretrained_weights_path: None

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

# Unet++

## BASELINE

unet_plus_plus:
  architecture:
    _target_: monai.networks.nets.BasicUNetPlusPlus
    out_channels: 1
    spatial_dims: 2         
    in_channels: 3
    features: [32, 64, 128, 256, 512, 32]
    deep_supervision: False

  temporal_setting:
    temporal_mode: none

unet_plus_plus_resnet18:
  architecture:
    _target_: surgical_copilot.models.segmentation_smp.SMPUNetPlusPlus
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1

  temporal_setting:
    temporal_mode: none

# SWIN U-NET

## BASELINE

swin_unetr:
  architecture:
    _target_: monai.networks.nets.SwinUNETR
    img_size: [640, 480]
    in_channels: 3
    out_channels: 1
    feature_size: 48
    spatial_dims: 2 # generally SwinUNETR is used with 3D image. In this way we can manage 2D frame
    use_checkpoint: True

  temporal_setting:
    temporal_mode: none

## YOLO

## BASELINE

yolo_v8_seg:
  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.CustomYOLOSemantic
    num_classes: 1
    num_masks: 32

  temporal_setting:
    temporal_mode: none

## EARLY FUSION

yolo_early_fusion_warmup_on:
  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.CustomYOLOSemantic
    in_channels: 4 # 3 channels RGB + 1 mask t-1 channel
    num_classes: 1
    num_masks: 32
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/CustomYOLOSemantic/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "early_fusion"
    temporal_target_layer: "yolo.backbone.stem.0.conv.weight"
    warmup_epochs: 5

yolo_early_fusion_warmup_off:
  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.CustomYOLOSemantic
    in_channels: 4 # 3 channels RGB + 1 mask t-1 channel
    num_classes: 1
    num_masks: 32

  temporal_setting:
    temporal_mode: "early_fusion"
    temporal_target_layer: None
    warmup_epochs: 0

## LATE FUSION

### WARMUP ON

yolo_late_fusion_gru_warmup_on:

  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.YOLOLateFusionTemporalSequential
    in_channels: 3
    num_classes: 1
    num_masks: 32
    recurrent_type: "gru"
    recurrent_layers: 1
    freeze_backbone: True
    warmup_epochs: 5
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/CustomYOLOSemantic/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: "yolo.backbone.stem.conv.weight"

yolo_late_fusion_lstm_warmup_on:
  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.YOLOLateFusionTemporalSequential
    in_channels: 3
    num_classes: 1
    num_masks: 32
    recurrent_type: "lstm"
    freeze_backbone: True
    warmup_epochs: 5
    pretrained_weights_path: "/work/cvcs2026/DeepLook/results/weights/CustomYOLOSemantic/best_fold{fold_idx}.pth"

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: "yolo.backbone.stem.conv.weight"

## WARMUP OFF

yolo_late_fusion_gru_warmup_off:

  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.YOLOLateFusionTemporalSequential
    in_channels: 3
    num_classes: 1
    num_masks: 32
    recurrent_type: "gru"
    recurrent_layers: 1
    freeze_backbone: True
    warmup_epochs: 0
    pretrained_weights_path: None

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None

yolo_late_fusion_lstm_warmup_off:
  architecture:
    _target_: surgical_copilot.models.yolov8_seg.yolov8_seg_wrapper.YOLOLateFusionTemporalSequential
    in_channels: 3
    num_classes: 1
    num_masks: 32
    recurrent_type: "lstm"
    freeze_backbone: True
    warmup_epochs: 0
    pretrained_weights_path: None

  temporal_setting:
    temporal_mode: "late_fusion"
    temporal_target_layer: None
