defaults:
  - _self_
  - model: unet # Default: carica configs/model/unet.yaml
  - dataset: hemoset # Default: carica configs/dataset/hemoset.yaml
  - trainer: default # Default: carica configs/trainer/default.yaml

# Variabili globali
seed: 42
device: "cuda"
debug: False
